### ISSUE TITLE
Signature doesn't match on AWS when making POST request.

### ISSUE THREAD

**Issue by bot2x** [manningt/aws-signature-iot#2]
I used this code with some modification for generating the signature to make a POST request on AWS api gateway.
It works when I make a GET request. But the signature doesn't match when making a POST request. I think the problem is with the way I attach the body. I am sending the body as a json like -

> inputs.payload = "{\\"some\\":\\"thing\\"}";

What am I missing ?

**Comment by manningt** [comment]
Try double escaping the backslash-quote.  
In the shell-aws4-test, I had to add 2 backslashes before the backslash-quote to get it to work:
```
            if (inputs.payload != NULL) {
                printf("--data \"");
                //escape the quote characters
                for (size_t i = 0; i < strlen(inputs.payload); i++ ) {
                    if (strncmp(&inputs.payload[i],"\"", 1) == 0)
                        putchar('\\');
                    putchar(inputs.payload[i]);
                }
                printf("\" ");
```

**Comment by bot2x** [comment]
Actually, I used this for a project using stm32. I got it working. There were some small formatting issues. I've fixed them and got it working. Thank you for this.
